import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import AdminPanel from './AdminPanel.jsx';
import { apiFetch as fetch } from './api.js';
import './styles.css';

const demoCourses = [
  { id: 1, title: 'Digital Marketing', category: 'Marketing', tagline: 'Turn attention into momentum.', description: 'A practical studio for learning the systems behind modern growth: from the first scroll-stopping idea to a campaign you can measure.', outcomes: ['Build a channel strategy that earns attention', 'Launch and optimize paid social campaigns', 'Read analytics and turn signals into decisions'], curriculum: ['Foundations & positioning', 'Content systems & social', 'Paid ads laboratory', 'Email & retention', 'Analytics, reporting & capstone'], instructor_name: 'Ayesha Rahman', instructor_bio: 'Growth strategist and mentor who has helped early-stage teams turn messy marketing into repeatable systems.', image_url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85', duration_label: '6 weeks', schedule_label: 'Tue & Thu · 7:00 PM', mode: 'Live online', level: 'Beginner', fee: 42000, discount_fee: 34000, next_batch: '2026-10-12', seats_left: 8, featured: 1 },
  { id: 2, title: 'SEO', category: 'Marketing', tagline: 'Make your best work findable.', description: 'Learn the technical and creative craft of SEO with a live project that takes a real site from invisible to intentional.', outcomes: ['Research opportunities with confidence', 'Fix technical and on-page issues', 'Create an ethical growth roadmap'], curriculum: ['Search intent & keyword research', 'On-page architecture', 'Technical SEO clinic', 'Authority & local search', 'Measurement & strategy'], instructor_name: 'Hamza Khan', instructor_bio: 'Technical SEO lead and former agency consultant with a thing for clean information architecture.', image_url: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?auto=format&fit=crop&w=1200&q=85', duration_label: '5 weeks', schedule_label: 'Mon & Wed · 7:00 PM', mode: 'Live online', level: 'Intermediate', fee: 38000, discount_fee: 30000, next_batch: '2026-10-19', seats_left: 12, featured: 1 },
  { id: 3, title: 'Content Writing', category: 'Creative', tagline: 'Find your voice. Then get paid for it.', description: 'Write clear, persuasive content people actually want to read. Leave with a portfolio, a process, and the confidence to pitch.', outcomes: ['Write for humans and search engines', 'Edit with a sharper eye', 'Package your work for freelance clients'], curriculum: ['Voice, clarity & structure', 'Blogs that earn attention', 'Conversion copywriting', 'Editing & feedback', 'Freelance foundations'], instructor_name: 'Mariam Ali', instructor_bio: 'Editorial director and writing coach who believes the best writing sounds like a person, not a brochure.', image_url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=85', duration_label: '4 weeks', schedule_label: 'Sat · 11:00 AM', mode: 'Live online', level: 'Beginner', fee: 28000, discount_fee: 22000, next_batch: '2026-11-07', seats_left: 16, featured: 0 },
  { id: 4, title: 'Web Development', category: 'Technology', tagline: 'Ship your first real thing.', description: 'A fundamentals-first build lab for turning ideas into responsive, deployed websites with HTML, CSS and JavaScript.', outcomes: ['Build responsive interfaces from scratch', 'Use JavaScript to make pages feel alive', 'Deploy a polished project to the web'], curriculum: ['HTML & the web', 'CSS systems & responsive layouts', 'JavaScript essentials', 'Build week', 'Deploy, review & next steps'], instructor_name: 'Omar Siddiqui', instructor_bio: 'Product engineer and patient teacher who makes the web feel less mysterious, one shipped project at a time.', image_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=85', duration_label: '8 weeks', schedule_label: 'Tue & Thu · 8:00 PM', mode: 'Live online', level: 'Beginner', fee: 52000, discount_fee: 42000, next_batch: '2026-10-26', seats_left: 5, featured: 1 }
];

const money = (value) => `PKR ${Number(value).toLocaleString('en-PK')}`;
const formatDate = (value) => new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

function App() {
  const [courses, setCourses] = useState([]);
  const [filters, setFilters] = useState({ search: '', category: 'All', level: 'All' });
  const [selected, setSelected] = useState(null);
  const [showEnroll, setShowEnroll] = useState(false);
  const [showAuth, setShowAuth] = useState(false);
  const [showDashboard, setShowDashboard] = useState(false);
  const [showAdmin, setShowAdmin] = useState(false);
  const [batches, setBatches] = useState([]);
  const [enrollmentError, setEnrollmentError] = useState('');
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams();
    if (filters.search) params.set('search', filters.search);
    if (filters.category !== 'All') params.set('category', filters.category);
    if (filters.level !== 'All') params.set('level', filters.level);
    fetch(`/api/courses?${params}`)
      .then((response) => response.ok ? response.json() : Promise.reject())
      .then(setCourses)
      .catch(() => setCourses(demoCourses));
  }, [filters]);

  useEffect(() => {
    if (!showEnroll || !selected) return;
    fetch(`/api/courses/${selected.id}/batches`).then((response) => response.ok ? response.json() : Promise.reject()).then(setBatches).catch(() => setBatches([]));
  }, [showEnroll, selected]);

  const filtered = courses.length ? courses : demoCourses;
  const featured = filtered.filter((course) => course.featured);
  const openCourse = (course) => { setSelected(course); setSubmitted(false); setEnrollmentError(''); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const handleEnroll = async (event) => {
    event.preventDefault();
    const body = Object.fromEntries(new FormData(event.currentTarget));
    body.courseId = selected.id;
    try { const response = await fetch('/api/enrollments', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(localStorage.getItem('northstar_token') ? { Authorization: `Bearer ${localStorage.getItem('northstar_token')}` } : {}) }, body: JSON.stringify(body) }); if (!response.ok) { const result = await response.json(); setEnrollmentError(result.message || 'Unable to submit this application.'); return; } } catch { setEnrollmentError('The enrollment service is unavailable. Please try again.'); return; }
    setSubmitted(true);
  };

  return <>
    <header className="site-header">
      <a className="brand" href="#top" onClick={() => setSelected(null)}><span className="brand-mark">N</span><span>northstar<span className="brand-dot">.</span></span></a>
      <nav><a href="#courses">Courses</a><a href="#about">About</a><a href="#instructors">Instructors</a><a href="#faq">FAQ</a></nav>
      <div className="header-actions">{localStorage.getItem('northstar_role') === 'admin' && <button className="login-link" onClick={() => setShowAdmin(true)}>Admin</button>}<button className="login-link" onClick={() => localStorage.getItem('northstar_token') ? setShowDashboard(true) : setShowAuth(true)}>{localStorage.getItem('northstar_token') ? 'Student portal' : 'Sign in'}</button><button className="button button-dark" onClick={() => { setSelected(null); document.querySelector('#courses').scrollIntoView({ behavior: 'smooth' }); }}>Explore courses <span>↗</span></button></div>
    </header>

    <main id="top">
      {showAdmin ? <AdminPanel onBack={() => setShowAdmin(false)} /> : showDashboard ? <StudentDashboard onBack={() => setShowDashboard(false)} /> : selected ? <CourseDetail course={selected} onBack={() => setSelected(null)} onEnroll={() => setShowEnroll(true)} /> : <>
        <section className="hero">
          <div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Live cohorts · Built for momentum</div><h1>Learn skills that <em>move</em> you forward.</h1><p>Practical, mentor-led courses for the next chapter of your career. Learn by doing, with people who are doing the work.</p><div className="hero-ctas"><button className="button button-dark" onClick={() => document.querySelector('#courses').scrollIntoView({ behavior: 'smooth' })}>Find your course <span>↗</span></button><a className="text-link" href="#why">Why Northstar <span>↓</span></a></div><div className="hero-proof"><div className="avatars"><span>AR</span><span>HK</span><span>MA</span><span>+2k</span></div><span>Loved by <strong>2,000+ learners</strong></span></div></div>
          <div className="hero-art"><div className="sun-shape" /><div className="hero-note note-top"><span className="note-icon">✦</span><div><strong>Learn in public</strong><small>Projects over lectures</small></div></div><div className="hero-photo"><img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1100&q=85" alt="Students collaborating around a table" /></div><div className="hero-note note-bottom"><span className="note-check">✓</span><div><strong>Next cohort</strong><small>Starts Oct 12 · 8 seats left</small></div></div><div className="shape-label">MAKE<br /><span>your mark</span></div></div>
        </section>

        <section className="marquee"><span>Learn with intent</span><b>✦</b><span>Build with confidence</span><b>✦</b><span>Grow with community</span><b>✦</b><span>Learn with intent</span></section>
        <section className="course-section" id="courses"><div className="section-intro"><div><div className="eyebrow">01 / Your next move</div><h2>Courses for curious<br /><em>people.</em></h2></div><p>Every Northstar course is built around a real outcome: a skill you can use, a project you can show, and a next step that feels closer.</p></div><div className="course-toolbar"><div className="search-box"><span>⌕</span><input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Search courses" /></div><div className="filter-group"><button className={filters.category === 'All' ? 'active' : ''} onClick={() => setFilters({ ...filters, category: 'All' })}>All courses</button><button className={filters.category === 'Marketing' ? 'active' : ''} onClick={() => setFilters({ ...filters, category: 'Marketing' })}>Marketing</button><button className={filters.category === 'Technology' ? 'active' : ''} onClick={() => setFilters({ ...filters, category: 'Technology' })}>Technology</button><button className={filters.level === 'Beginner' ? 'active' : ''} onClick={() => setFilters({ ...filters, level: 'Beginner' })}>Beginner</button></div></div><div className="course-grid">{(featured.length ? featured : filtered).map((course) => <CourseCard key={course.id} course={course} onOpen={openCourse} />)}</div></section>
        <section className="why-section" id="why"><div className="why-image"><img src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1100&q=85" alt="A mentor speaking with learners" /><div className="image-caption">Real people.<br /><em>Real progress.</em></div></div><div className="why-copy"><div className="eyebrow">02 / The Northstar way</div><h2>Less theory.<br /><em>More becoming.</em></h2><p>We believe learning should change what you can do, not just what you know. That means small cohorts, honest feedback, and work that makes it out into the world.</p><div className="principles"><div><span>01</span><strong>Human-sized cohorts</strong><p>Get seen, supported, and challenged by mentors who remember your name.</p></div><div><span>02</span><strong>Work you can show</strong><p>Leave with a portfolio of proof, not a folder of forgotten PDFs.</p></div><div><span>03</span><strong>Community that stays</strong><p>Your cohort becomes your network, long after the last class ends.</p></div></div></div></section>
        <section className="about-section" id="about"><div><div className="eyebrow">03 / Why we exist</div><h2>Learning should<br /><em>open doors.</em></h2></div><div className="about-copy"><p>Northstar is a practical learning studio for people building their next chapter. We pair useful skills with honest mentorship, so progress feels visible from the first week.</p><div className="stats"><div><strong>2,000+</strong><span>learners supported</span></div><div><strong>4.9/5</strong><span>average learner rating</span></div><div><strong>86%</strong><span>finish a real project</span></div></div></div></section>
        <section className="instructor-section" id="instructors"><div className="section-intro"><div><div className="eyebrow">04 / The people teaching</div><h2>Learn from people<br /><em>in the arena.</em></h2></div><p>Our instructors are working practitioners first. They bring current tools, useful stories, and feedback that respects your time.</p></div><div className="instructor-grid">{[...new Map(filtered.map((course) => [course.instructor_name, course])).values()].slice(0, 3).map((course) => <article className="instructor-card" key={course.instructor_name}><img src={course.image_url} alt={course.instructor_name} /><div><span>{course.category}</span><h3>{course.instructor_name}</h3><p>{course.instructor_bio}</p></div></article>)}</div></section>
        <section className="quote-section" id="stories"><div className="quote-mark">“</div><blockquote>Northstar gave me the structure to stop waiting until I felt ready. I launched my first client campaign before the course even ended.</blockquote><div className="quote-author"><span className="author-avatar">SZ</span><span><strong>Sarah Zahid</strong><small>Digital Marketing graduate · 2025</small></span></div></section>
        <section className="faq-section" id="faq"><div><div className="eyebrow">05 / Good questions</div><h2>Before you<br /><em>begin.</em></h2><p>Still unsure? Write to <a className="text-link" href="mailto:hello@northstar.pk">hello@northstar.pk</a> and a real person will help.</p></div><div className="faq-list"><details open><summary>Are the courses live or self-paced?</summary><p>Our core courses are live online cohorts with scheduled classes, feedback, and a small group of peers. Recordings are available for review.</p></details><details><summary>Do I need experience before joining?</summary><p>No. Each course shows its recommended level. Beginner courses start from first principles and give you a clear path to your first project.</p></details><details><summary>Can I pay in installments?</summary><p>Yes. Choose pay later during enrollment and our admissions team will share bank transfer and installment options for your course.</p></details><details><summary>What happens after I apply?</summary><p>We review your application, confirm the cohort details, and send a simple payment and onboarding guide by email.</p></details></div></section>
        <section className="contact-strip" id="contact"><div><div className="eyebrow">06 / Ready when you are</div><h2>Your next chapter<br /><em>starts here.</em></h2></div><div><p>Questions about a course, payment, or whether this is right for you? We’re human. Talk to us.</p><a href="mailto:hello@northstar.pk" className="text-link">hello@northstar.pk ↗</a></div><button className="button button-dark" onClick={() => document.querySelector('#courses').scrollIntoView({ behavior: 'smooth' })}>Explore courses <span>↗</span></button></section>
      </>}
    </main>
    <footer><a className="brand" href="#top"><span className="brand-mark">N</span><span>northstar<span className="brand-dot">.</span></span></a><span>© 2026 Northstar Learning</span><span>Made for people in motion.</span></footer>
    {showAuth && <AuthModal onClose={() => setShowAuth(false)} onAuthenticated={() => { setShowAuth(false); setShowDashboard(true); }} />}
    {showEnroll && <div className="modal-backdrop" onClick={(e) => e.target === e.currentTarget && setShowEnroll(false)}><div className="modal">{submitted ? <div className="success"><span>✓</span><h2>You’re on your way.</h2><p>We’ve received your interest in <strong>{selected.title}</strong>. Our team will reach out with the next steps.</p><button className="button button-dark" onClick={() => setShowEnroll(false)}>Done</button></div> : <><button className="modal-close" onClick={() => setShowEnroll(false)}>×</button><div className="eyebrow">Start your application</div><h2>Join {selected.title}.</h2><p className="modal-subtitle">Tell us a little about yourself. No pressure, just a first step.</p>{enrollmentError && <p className="auth-message">{enrollmentError}</p>}<form onSubmit={handleEnroll}><label>Full name<input required name="name" placeholder="Your name" /></label><label>Email address<input required type="email" name="email" placeholder="you@email.com" /></label><label>Phone number<input required name="phone" placeholder="+92 300 0000000" /></label><label>Choose a batch<select required name="batchId"><option value="">Select an available batch</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{formatDate(batch.starts_on)} · {batch.schedule_label} · {batch.capacity} seats</option>)}</select></label><label>Payment preference<select name="paymentMethod"><option value="pay_later">I’ll pay later / bank transfer</option><option value="card">Card payment</option></select></label><button className="button button-dark full" type="submit">Submit application <span>↗</span></button></form></>}</div></div>}
  </>;
}

function CourseCard({ course, onOpen }) { return <article className="course-card" onClick={() => onOpen(course)}><div className="course-image"><img src={course.image_url} alt={course.title} /><span className="course-badge">{course.level}</span><button className="arrow-button" aria-label={`View ${course.title}`}>↗</button></div><div className="course-card-body"><div className="course-meta"><span>{course.category}</span><span>{course.duration_label}</span></div><h3>{course.title}</h3><p>{course.tagline}</p><div className="course-price"><span>From <strong>{money(course.discount_fee || course.fee)}</strong></span><span className="seats">{course.seats_left} seats left</span></div></div></article> }
function AuthModal({ onClose, onAuthenticated }) { const [mode, setMode] = useState('login'); const [message, setMessage] = useState(''); const submit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/auth/${mode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }).catch(() => null); if (!response) { setMessage('Connect the MySQL database to create an account.'); return; } const result = await response.json(); if (!response.ok) { setMessage(result.message); return; } localStorage.setItem('northstar_token', result.token); localStorage.setItem('northstar_role', result.user.role); onAuthenticated(); }; return <div className="modal-backdrop" onClick={(event) => event.target === event.currentTarget && onClose()}><div className="modal"><button className="modal-close" onClick={onClose}>×</button><div className="eyebrow">Student account</div><h2>{mode === 'login' ? 'Welcome back.' : 'Start learning.'}</h2><p className="modal-subtitle">Track your applications, course progress, and certificates in one place.</p>{message && <p className="auth-message">{message}</p>}<form onSubmit={submit}>{mode === 'register' && <label>Full name<input required name="name" placeholder="Your name" /></label>}<label>Email address<input required type="email" name="email" placeholder="you@email.com" /></label><label>Password<input required minLength="8" type="password" name="password" placeholder="At least 8 characters" /></label><button className="button button-dark full" type="submit">{mode === 'login' ? 'Sign in' : 'Create account'} <span>↗</span></button></form><button className="auth-switch" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage(''); }}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Sign in'}</button></div></div> }
function AdminDashboard({ onBack }) { const [data, setData] = useState(null); const [error, setError] = useState(''); const token = localStorage.getItem('northstar_token'); const load = () => fetch('/api/admin/overview', { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.ok ? response.json() : Promise.reject()).then(setData).catch(() => setError('Admin access is unavailable. Please sign in with an admin account.')); useEffect(load, []); const updateStatus = async (id, status) => { await fetch(`/api/enrollments/${id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ status }) }); load(); }; return <section className="admin-page"><button className="back-link" onClick={onBack}>← Back to Northstar</button>{error ? <div className="dashboard-empty"><div className="eyebrow">Admin console</div><h1>Access<br /><em>required.</em></h1><p>{error}</p></div> : data ? <><div className="dashboard-header"><div><div className="eyebrow">Admin console</div><h1>Good morning, <em>team.</em></h1><p>Keep the learning engine moving.</p></div><span className="admin-date">Live overview</span></div><div className="admin-stats"><div><span>Students</span><strong>{data.stats.students}</strong></div><div><span>Enrollments</span><strong>{data.stats.enrollments}</strong></div><div><span>Pending review</span><strong>{data.stats.pending}</strong></div></div><div className="admin-table-wrap"><div className="eyebrow">Recent applications</div><div className="admin-table">{data.recent.length ? data.recent.map((item) => <div className="admin-row" key={item.id}><div><strong>{item.student_name}</strong><small>{item.student_email} · {item.title}</small></div><span className={`status-pill status-${item.status}`}>{item.status}</span>{item.status === 'pending' && <div className="admin-actions"><button onClick={() => updateStatus(item.id, 'confirmed')}>Approve</button><button onClick={() => updateStatus(item.id, 'cancelled')}>Reject</button></div>}</div>) : <p className="admin-empty">No applications yet.</p>}</div></div></> : <div className="dashboard-loading">Loading admin overview...</div>}</section> }
function StudentDashboard({ onBack }) { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { fetch('/api/student/dashboard', { headers: { Authorization: `Bearer ${localStorage.getItem('northstar_token')}` } }).then((response) => response.ok ? response.json() : Promise.reject()).then(setData).catch(() => setError('Connect MySQL and sign in to load your student portal.')); }, []); return <section className="dashboard"><button className="back-link" onClick={onBack}>← Back to Northstar</button>{error ? <div className="dashboard-empty"><div className="eyebrow">Student portal</div><h1>Your learning<br /><em>starts here.</em></h1><p>{error}</p></div> : data ? <><div className="dashboard-header"><div><div className="eyebrow">Student portal</div><h1>Hello, <em>{data.user.name.split(' ')[0]}.</em></h1><p>{data.user.email}</p></div><button className="button button-dark" onClick={() => { localStorage.removeItem('northstar_token'); onBack(); }}>Sign out</button></div><div className="dashboard-grid"><div className="dashboard-main"><div className="eyebrow">Your courses</div>{data.enrollments.length ? data.enrollments.map((item) => <article className="enrollment-card" key={item.id}><div><span className="status-pill">{item.status}</span><h2>{item.title}</h2><p>{item.starts_on ? `Batch starts ${formatDate(item.starts_on)} · ${item.schedule_label}` : 'Application received · batch details coming soon'}</p></div><span className="dashboard-arrow">↗</span></article>) : <div className="dashboard-empty"><h2>Your first course is waiting.</h2><p>Explore the catalogue and apply to a live cohort when you’re ready.</p><button className="button button-dark" onClick={onBack}>Browse courses <span>↗</span></button></div>}</div><aside className="profile-card"><div className="profile-avatar">{data.user.name.slice(0, 2).toUpperCase()}</div><h3>{data.user.name}</h3><p>Member since {formatDate(data.user.created_at)}</p><div className="profile-line"><span>Email</span><strong>{data.user.email}</strong></div><div className="profile-line"><span>Account</span><strong>{data.user.email_verified ? 'Verified' : 'Pending verification'}</strong></div></aside></div></> : <div className="dashboard-loading">Loading your portal...</div>}</section> }
function CourseDetail({ course, onBack, onEnroll }) { return <section className="detail"><button className="back-link" onClick={onBack}>← Back to all courses</button><div className="detail-hero"><div className="detail-copy"><div className="eyebrow">{course.category} · {course.level}</div><h1>{course.title}<br /><em>{course.tagline}</em></h1><p>{course.description}</p><button className="button button-dark" onClick={onEnroll}>Enroll now <span>↗</span></button></div><img src={course.image_url} alt={course.title} /></div><div className="detail-content"><div><div className="eyebrow">What you’ll leave with</div><h2>A course with<br /><em>somewhere to go.</em></h2>{course.outcomes.map((item) => <div className="outcome" key={item}><span>✓</span>{item}</div>)}</div><aside><div className="detail-price">{course.discount_fee && <del>{money(course.fee)}</del>}<strong>{money(course.discount_fee || course.fee)}</strong><small>one-time fee · payment plans available</small></div><div className="info-row"><span>Next batch</span><strong>{formatDate(course.next_batch)}</strong></div><div className="info-row"><span>Schedule</span><strong>{course.schedule_label}</strong></div><div className="info-row"><span>Format</span><strong>{course.mode}</strong></div><div className="info-row"><span>Instructor</span><strong>{course.instructor_name}</strong></div></aside></div><div className="curriculum"><div className="eyebrow">Inside the course</div><h2>Five weeks of<br /><em>forward motion.</em></h2>{course.curriculum.map((item, index) => <div className="module" key={item}><span>0{index + 1}</span><strong>{item}</strong><span>+</span></div>)}</div></section> }

createRoot(document.getElementById('root')).render(<App />);
